name = "web-order-auto-lock"
main = "workers/auto-lock.ts"
compatibility_date = "2026-07-30"

[triggers]
crons = ["59 15 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "order"
database_id = "e238e4a3-259a-4fc3-a345-710710850249"
migrations_dir = "migrations"
