import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { spawn, spawnSync } from "node:child_process";
import { join, resolve } from "node:path";

const root = process.cwd();
const persistDir = resolve(root, ".wrangler/e2e");
const configPath = join(persistDir, "wrangler.toml");
const varsPath = resolve(root, ".dev.vars");
const wrangler = resolve(root, "node_modules/.bin/wrangler");
const originalVars = existsSync(varsPath) ? readFileSync(varsPath, "utf8") : null;

rmSync(persistDir, { recursive: true, force: true });
mkdirSync(persistDir, { recursive: true });
writeFileSync(configPath, `name = "collaborative-ordering-e2e"\ncompatibility_date = "2026-07-29"\n\n[[d1_databases]]\nbinding = "DB"\ndatabase_name = "ordering-e2e-db"\ndatabase_id = "ordering-e2e-db"\nmigrations_dir = "${resolve(root, "migrations").replaceAll("\\", "\\\\")}"\n`);
writeFileSync(varsPath, "# Generated by scripts/start-e2e.mjs; test-only values.\nADMIN_PASSWORD=e2e-admin-password\nADMIN_SESSION_SECRET=e2e-session-secret-32-characters-minimum\n");

const env = {
  ...process.env,
  WRANGLER_LOG_PATH: join(persistDir, "wrangler.log"),
};

function restoreVars() {
  if (originalVars === null) rmSync(varsPath, { force: true });
  else writeFileSync(varsPath, originalVars);
}

const migrations = spawnSync(wrangler, [
  "d1", "migrations", "apply", "DB",
  "--config", configPath,
  "--local",
  "--persist-to", persistDir,
], { cwd: root, env, stdio: "inherit" });

if (migrations.status !== 0) {
  restoreVars();
  process.exit(migrations.status ?? 1);
}

const server = spawn(wrangler, [
  "pages", "dev", "dist",
  "--d1", "DB=ordering-e2e-db",
  "--persist-to", persistDir,
  "--compatibility-date", "2026-07-29",
  "--ip", "127.0.0.1",
  "--port", "8788",
  "--log-level", "warn",
  "--show-interactive-dev-session=false",
], { cwd: root, env, stdio: "inherit" });

let stopping = false;
function stop(signal) {
  if (stopping) return;
  stopping = true;
  restoreVars();
  if (!server.killed) server.kill(signal);
}

process.on("SIGINT", () => stop("SIGINT"));
process.on("SIGTERM", () => stop("SIGTERM"));
process.on("exit", restoreVars);
server.on("exit", (code, signal) => {
  restoreVars();
  if (!stopping) process.exitCode = code ?? (signal ? 1 : 0);
});
